# Generated by Django 3.0.5 on 2020-04-13 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='Mark',
            field=models.BooleanField(default=False),
        ),
    ]
