# Generated by Django 3.0.5 on 2020-04-13 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_schedule_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chore',
            name='description',
            field=models.CharField(max_length=250),
        ),
    ]
