# Generated by Django 3.0.5 on 2020-04-13 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200413_0448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='chroe',
            new_name='chore',
        ),
    ]
